# Домашнє завдання до теми "Розширені методи обробки даних у Pandas"

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [2]:
import pandas as pd
data_path = '/content/drive/MyDrive/supermarket_sales.csv'
df = pd.read_csv(data_path)

1. Відсортуйте дані за спаданням ціни товара ('Unit price') і виведіть 5 перших рядочків на екран.

In [5]:
df.sort_values (by = "Unit price", ascending=False).head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
983,148-41-7930,C,Naypyitaw,Normal,Male,Health and beauty,99.96,7,34.986,734.706,1/23/2019,10:33,Cash,699.72,4.761905,34.986,6.1
122,219-22-9386,B,Mandalay,Member,Male,Sports and travel,99.96,9,44.982,944.622,3/9/2019,17:26,Credit card,899.64,4.761905,44.982,4.2
930,641-62-7288,B,Mandalay,Normal,Male,Home and lifestyle,99.92,6,29.976,629.496,3/24/2019,13:33,Ewallet,599.52,4.761905,29.976,7.1
494,437-53-3084,B,Mandalay,Normal,Male,Fashion accessories,99.89,2,9.989,209.769,2/26/2019,11:48,Ewallet,199.78,4.761905,9.989,7.1
283,667-92-0055,A,Yangon,Member,Male,Health and beauty,99.83,6,29.949,628.929,3/4/2019,15:02,Ewallet,598.98,4.761905,29.949,8.5

2. Знайдіть інвойс (рядок в даних) в категорії товарів `Electronic accessories`, в якому був куплений товар з найбільшою кількістю і найбільшою ціною. Виведіть цей рядок даних на екран.

In [8]:
df [df ['Product line'] == 'Electronic accessories'].sort_values (by=["Quantity", "Unit price"], ascending= False).head(1)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
105,704-48-3927,A,Yangon,Member,Male,Electronic accessories,88.67,10,44.335,931.035,1/12/2019,14:50,Ewallet,886.7,4.761905,44.335,7.3

і на всякий випадок:

In [19]:
df [df ['Product line'] == 'Electronic accessories'].sort_values (by=["Unit price", "Quantity"], ascending= False).head(1)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Rating Category,Hour
209,817-69-8206,B,Mandalay,Normal,Female,Electronic accessories,99.73,9,44.8785,942.4485,3/2/2019,19:42,Credit card,897.57,4.761905,44.8785,6.5,Medium,19

3.1. Створіть нову колонку в даних `Rating Category`, яка визначає категорію рейтингу (`Rating`): високий, середній чи низький за наступним правилом:
- якщо рейтинг вищий або рівний 8 - то він високий (`High`)
- якщо рейтинг від 6 до 8 не включаючи - то він середній (`Medium`)
- інакше - низький (`Low`).

In [12]:
df ['Rating Category'] = df.Rating.apply (lambda x: 'High' if x >= 8 else ('Medium' if x > 6 else 'Low'))
df.head ()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Rating Category
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1,High
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6,High
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4,Medium
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4,High
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3,Low

3.2. Виведіть, який відсоток даних становить кожне зі значень категорій рейтингу.

In [13]:
df ['Rating Category'].value_counts (normalize=True)

Rating Category
Low       0.341
Medium    0.330
High      0.329
Name: proportion, dtype: float64

4.1. Запустіть код нижче аби створити змінну `time`. Ця змінна містить час в форматі "година:хвилина". Напишіть функцію `get_hour`, яка буде зі змінної формату як `time` дістати лише години і конвертувати їх у тип `int`.

Запустіть написану функцію на змінній `time` та перевірте правильність роботи функції.

In [14]:
time = '11:28'

In [16]:
def get_hour (time_str: str) -> int:
  parts = time_str.split (':')
  hour_int = int (parts[0])
  return hour_int
get_hour (time)

11

4.2. З допомогою функції `get_hour` і метода `DataFrame.apply()` створіть нову колонку `Hour` в нашому наборі даних, яка буде містити години здійснення покупки, обчислені на основі часу здійснення покупки `Time`.

In [17]:
df ['Hour'] = df.Time.apply(get_hour)

4.3. Виведіть кількість значень за кожною годиною покупки і дайте відповідь "О яких годинах найбільше здійснюють покупок покупці і чому на Ваш погляд саме о цих годинах? Чи це слогічно, що найбільше покупок саме в ці години?".

In [18]:
df.Hour.value_counts()

Hour
19    113
13    103
15    102
10    101
18     93
11     90
12     89
14     83
16     77
20     75
17     74
Name: count, dtype: int64

Найбільше покупці роблять покупок о 10, 13, 15 і 19 годинах. Це, на мою думку, логічно - години приблизно співпадають з часом коли люди прямують на роботу/з роботи плюс години обідньої перерви, саме час робити покупки.

5. Виведіть середнє значення чеку (`Total`) для покупок в містах, наявних в даних, за допомогою функції `groupby`.

In [20]:
df.groupby ('City')['Total'].mean()

City
Mandalay     319.872506
Naypyitaw    337.099715
Yangon       312.354031
Name: Total, dtype: float64

6. Виведіть кількість покупок, середнє, мінімальне та максимальне значення для загальної суми чеку (Total) в містах, наявних в даних, за допомогою функції groupby.
Зробіть висновки з цих показників та дайте рекомендації для мережі супермаркетів.

In [21]:
df.groupby ('City')['Total'].agg (['count', 'mean', 'min', 'max']).round (3)

           count     mean     min      max
City
Mandalay     332  319.873  18.638  1022.49
Naypyitaw    328  337.100  10.678  1042.65
Yangon       340  312.354  12.694  1039.29

###Кількість покупок
Yangon має найбільшу кількість покупок, Naypyitaw - найменшу. Але загалом цей показник приблизно рівний у всіх містах, різниця становить менше 5%.
###Середній чек
Тут ситуація діаметрально протилежна Yangon - найменший показник при найбільшій кількості покупок, Naypyitaw - найбільший середній чек при найменшій кількості покупок, отже тут купують рідше, але на більшу суму. Все ж загалом теж можна вважати ситуацію більш-менш однаковою у всіх трьох містах.
###Мінімальний чек
Свідчить про наявність невеликих покупок у всіх локаціях. У місті Mandalay мінімальний чек трохи більший ніж у інших.
###Максимальний чек
Також приблизно однакова ситуація у всіх трьох містах.
##Рекомендації
Як і для будь-якої торгівельної організації: необхідно збільшувати загальний прибуток. Це можна зробити за рахунок збільшення кількості покупців шляхом інвестицій в маркетингові кампанії, забезпечення високого рівня комфорту і сервісу. Крім цього можна підвищити середній чек шляхом програм лояльності, акцій, знижок на наступні покупки, розширення асортименту.

7. Ми внесли деякі зміни в наш набір даних, тож, давайте запишемо результат у файл. Запишіть оновлену версію даних у файл `supermarket_sales_enriched.csv`. Зверніть увагу, аби не записати нічого зайвого, наприклад, індекси рядків нам в файлі не потрібні, оскільки вони стандартні.

In [22]:
df.to_csv ('supermarket_sales_enriched.csv', index=False)